extension_to_language = {
    ".py": "Python",
    ".js": "JavaScript",
    ".html": "HTML",
    ".css": "CSS",
    ".md": "Markdown",
    ".json": "JSON",
    ".txt": "Text",
    ".xml": "XML",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".sh": "Shell",
    ".bat": "Batch",
    ".ps1": "PowerShell",
    ".java": "Java",
    ".c": "C",
    ".cpp": "C++",
    ".h": "C++",
    ".cs": "C#",
    ".go": "Go",
    ".php": "PHP",
    ".rb": "Ruby",
    ".rs": "Rust",
    ".swift": "Swift",
    ".kt": "Kotlin",
    ".clj": "Clojure",
    ".scala": "Scala",
    ".pl": "Perl",
    ".jl": "Julia",
    ".r": "R",
    ".dart": "Dart",
    ".lua": "Lua",
    ".coffee": "CoffeeScript",
    ".vb": "Visual Basic",
    ".ts": "TypeScript",
    ".hs": "Haskell",
    ".erl": "Erlang",
    ".ex": "Elixir",
    ".elm": "Elm",
    ".pas": "Pascal",
    ".lisp": "Lisp",
    ".scm": "Scheme",
    ".cl": "Common Lisp",
    ".ml": "OCaml",
    ".fs": "F#",
    ".fsi": "F#",
    ".v": "Coq",
    ".thy": "Isabelle",
    ".ml4": "OCaml",
    ".rkt": "Racket",
    ".exs": "Elixir",
    ".pyc": "Python Bytecode",
    ".iml": "PyCharm Project File",
}
