mime_to_language = {
    "application/x-python-code": "Python",
    "application/javascript": "JavaScript",
    "text/html": "HTML",
    "text/css": "CSS",
    "text/markdown": "Markdown",
    "application/json": "JSON",
    "text/plain": "Text",
    "application/xml": "XML",
    "application/x-yaml": "YAML",
    "application/x-shellscript": "Shell",
    "application/x-bat": "Batch",
    "application/x-powershell": "PowerShell",
    "text/x-java-source": "Java",
    "text/x-c": "C",
    "text/x-c++": "C++",
    "text/x-csharp": "C#",
    "text/x-go": "Go",
    "application/x-httpd-php": "PHP",
    "application/x-ruby": "Ruby",
    "text/rust": "Rust",
    "text/x-swift": "Swift",
    "text/x-kotlin": "Kotlin",
    "text/x-clojure": "Clojure",
    "text/x-scala": "Scala",
    "text/x-perl": "Perl",
    "application/x-julia": "Julia",
    "text/x-r-source": "R",
    "application/dart": "Dart",
    "text/x-lua": "Lua",
    "text/coffeescript": "CoffeeScript",
    "text/x-vb": "Visual Basic",
    "application/typescript": "TypeScript",
    "text/x-haskell": "Haskell",
    "text/x-erlang": "Erlang",
    "application/x-elixir": "Elixir",
    "application/x-elm": "Elm",
    "text/x-pascal": "Pascal",
    "text/x-lisp": "Lisp",
    "text/x-scheme": "Scheme",
    "text/x-common-lisp": "Common Lisp",
    "text/x-ocaml": "OCaml",
    "text/x-fsharp": "F#",
    "text/x-coq": "Coq",
    "application/x-isabelle": "Isabelle",
    "application/x-racket": "Racket",
}
